### ISSUE TITLE
Shrink/adjust size of skates

### ISSUE THREAD

**Issue by Hiderlink20** [SGiygas/BrcCustomCharacters#1]
When I shrink the skates in the unity, they don’t appear to be any smaller than they are.  I’d like to adjust their size so they fit the character’s feet.  Is there something I am overlooking with this issue?

**Comment by Hiderlink20** [comment]
Ok now with the recent update, I'm not able to make proper changes to the props and skates because they vanish when I go to edit them in the scene window and only appear on the prefab.  Also, the update to the plugin rendered my past mods useless, so is there a way to udpate them to work for the new version without having to start over?

**Comment by SGiygas** [comment]
You can lock the inspector to keep the preview while you edit transforms.
In the future please don't use the issues section here for support with Unity.
This section is for issues with the code in the repo.
